export const ERROR_CONFIG = {
  USER: {
    NOT_FOUND: "USER_NOT_FOUND",
    UPDATE_FAILED: "USER_UPDATE_FAILED",
    DATA_INVALID: "USER_DATA_INVALID",
    CREATE_FAILED: "CREATE_USER_FAILED",
    DUPLICATE: "USER_DATA_DUPLICATE",
    INVALID_EMAIL_OR_PASSWORD: "INVALID_EMAIL_OR_PASSWORD",
  },

  CATEGORY: {
    NOT_FOUND: "CATEGORY_NOT_FOUND",
    CREATE_FAILED: "CATEGORY_CREATE_FAILED",
    UPDATE_FAILED: "CATEGORY_UPDATE_FAILED",
    DELETE_FAILED: "CATEGORY_DELETE_FAILED",
    DUPLICATE_NAME: "CATEGORY_DUPLICATE_NAME",
  },

  AUTH: {
    LOGIN_FAILED: "AUTH_LOGIN_FAILED",
    TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
    INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
    SESSION_EXPIRED: "AUTH_SESSION_EXPIRED",
    PERMISSION_DENIED: "AUTH_PERMISSION_DENIED",
    ACCOUNT_LOCKED: "AUTH_ACCOUNT_LOCKED",
    SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
    FORBIDDEN: "FORBIDDEN",
    UNAUTHORIZED: "UNAUTHORIZED",
    INACTIVE_PROFILE: "AUTH_INACTIVE_PROFILE",
  },

  SYSTEM: {
    NETWORK_ERROR: "NETWORK_ERROR",
    SERVER_ERROR: "SERVER_ERROR",
    TIMEOUT_ERROR: "TIMEOUT_ERROR",
    DATABASE_ERROR: "DATABASE_ERROR",
    EXTERNAL_SERVICE_ERROR: "EXTERNAL_SERVICE_ERROR",
    CONFIGURATION_ERROR: "CONFIGURATION_ERROR",
    INTERNAL_ERROR_CODE: "ERR-5000",
  },

  VALIDATION: {
    REQUIRED_FIELD: "VALIDATION_REQUIRED_FIELD",
    INVALID_FORMAT: "VALIDATION_INVALID_FORMAT",
    INVALID_RANGE: "VALIDATION_INVALID_RANGE",
    DUPLICATE_VALUE: "VALIDATION_DUPLICATE_VALUE",
    CROSS_FIELD_VALIDATION: "VALIDATION_CROSS_FIELD_VALIDATION",
  },

  PLAID: {
    LINK_TOKEN_FAILED: "PLAID_LINK_TOKEN_FAILED",
    EXCHANGE_TOKEN_FAILED: "PLAID_EXCHANGE_TOKEN_FAILED",
    AUTH_FAILED: "PLAID_AUTH_FAILED",
    INVALID_REQUEST: "PLAID_INVALID_REQUEST",
    API_ERROR: "PLAID_API_ERROR",
    ACCESS_TOKEN_NOT_FOUND: "ACCESS_TOKEN_NOT_FOUND",
    LINK_TOKEN_NOT_FOUND: "LINK_TOKEN_NOT_FOUND"
  },
};
